apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins-slave-nodejs-10
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: jenkins-slave-nodejs-10
