apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins
  namespace: default
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: template.${NAME}-slave-user
  stringData:
    password: ${SLAVE_USER_PASSWORD}
    username: jenkins-slave
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: template.${NAME}-github
  stringData:
    metadata.name: template.${NAME}-github
    password: ${GH_PASSWORD}
    username: ${GH_USERNAME}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: jenkins
- name: GH_USERNAME
  required: true
- description: GitHub Personal Access Token
  name: GH_PASSWORD
  required: true
- description: SLAVE_USER_PASSWORD
  displayName: SLAVE_USER_PASSWORD
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: SLAVE_USER_PASSWORD
